#user account services#

test_name: Create new user
stages: 
  - name: make sure that the user was created successfully
    request:
      url: http://localhost:2015/accounts/create-user
      method: PUT
      json: 
        username :  449user 
        email: testuser@gmail.com
        karma: 0
        headers:
          content-type: application/json
      response:
        status_code : 200

test_name: Create new user without email or username
stages: 
  - name: make sure that it gets the error response
    request:
      url: http://localhost:2015/accounts/create-user
      method: POST
      headers:
        content-type: application/json
      response:
        status_code : 404

test_name: increment of karma when posted
stages: 
  - name: make sure that it returns back successful status code
    request:
      url: http://localhost:2015/accounts/increment-karma/449user
      method: POST
      json: 
        username: 449user
      headers:
        content-type: application/json
      response:
        status_code : 200

test_name: increment of karma for different user
stages: 
  - name: make sure that it gets the error response
    request:
      url: http://localhost:2015/accounts/increment-karma/442user
      method: POST
      json: 
        username: 449user
      headers:
        content-type: application/json
      response:
        status_code : 404

test_name: decrement of karma when post was downvote or deleted
stages: 
  - name: make sure that it gets the successful status code
    request:
      url: http://localhost:2015/accounts/derement-karma/449user
      method: POST
      json: 
        username: 449user
        karma: i -= 1
      headers:
        content-type: application/json
      response:
        status_code : 200


test_name: decrement of karma for a different user 
stages: 
  - name: make sure that it gets the error response
    request:
      url: http://localhost:2015/accounts/decrement-karma/443user
      method: POST
      json: 
        username: 449user
        karma: i -= 1
      headers:
        content-type: application/json
      response:
        status_code : 404


test_name: deactivate the right account with username
stages: 
  - name: make sure that the user get deactivated with the right username successfully
    request:
      url: http://localhost:2015/accounts/deactivate_accounts/449user
      method: DELETE
      json:
        username: 449user
      headers:
        content-type: application/json
      response:
        status_code : 200


test_name: deactivate account with non-exisitng username
stages: 
  - name: make sure that the user did not get deactivated with non-existing username and returns error code
    request:
      url: http://localhost:2015/accounts/deactivate_accounts/455user
      method: DELETE
      json:
        username: 455user
      headers:
        content-type: application/json
      response:
        status_code : 404